### ISSUE TITLE
error: [Errno 2] No such file or directory: 'build\\bdist.win-amd64\\egg\\apex\\contrib\\sparsity\\permutation_search_kernels\\__pycache__\\call_permutation_search _kernels.cpython-38.pyc.2347378509744'

### ISSUE THREAD

**Issue by starstarb** [NVIDIA/apex#1376] opened 2022-05-06 03:18 UTC
**Describe the Bug**
 I  use         --python setup.py install   but got this error

error: [Errno 2] No such file or directory: 'build\\bdist.win-amd64\\egg\\apex\\contrib\\sparsity\\permutation_search_kernels\\__pycache__\\call_permutation_search _kernels.cpython-38.pyc.2347378509744'

who can help me ?
My environment is windows10, pytorch 1.9, CUDA 11.1

**Minimal Steps/Code to Reproduce the Bug**
 

**Expected Behavior**

**Environment**

**Comment by ptrblck** [comment] 2022-05-06 13:12
Closing as duplicate of https://github.com/NVIDIA/apex/issues/1375

**Closed by ptrblck** 2022-05-06 13:12 UTC
Labels: bug
