### ISSUE TITLE
Cannot import Adam Optimizer!

### ISSUE THREAD

**Issue by ben15021999** [NVIDIA/apex#1304] opened 2022-02-24 06:50 UTC
Last night, I could import FuseAdamV2 optimizer in fairseq source. However, in this morning, I try to re run on gg Colab, and it cannot import FuseAdamV2 anymore.

**Comment by TheWispy** [comment] 2022-02-24 11:53
Just ran into an issue with the latest version of apex as well on a docker image using tensorflow-2.7-gpu as a base.

Here's a snippet from our poetry pyproject file

```
transformers = "^4.16.2"
sentencepiece = "^0.1.96"
torchvision = "0.10.0=py39_cu111"
torch = "1.9.0=py39_cu111"
```

The exception we got was

```
raceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/transformers/file_utils.py", line 2704, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.8/dist-packages/transformers/sagemaker/__init__.py", line 19, in <module>
    from .trainer_sm import SageMakerTrainer
  File "/usr/local/lib/python3.8/dist-packages/transformers/sagemaker/trainer_sm.py", line 16, in <module>
    from ..trainer import Trainer
  File "/usr/local/lib/python3.8/dist-packages/transformers/trainer.py", line 147, in <module>
    from apex import amp
  File "/usr/local/lib/python3.8/dist-packages/apex/__init__.py", line 23, in <module>
    from . import transformer
  File "/usr/local/lib/python3.8/dist-packages/apex/transformer/__init__.py", line 4, in <module>
    from apex.transformer import pipeline_parallel
  File "/usr/local/lib/python3.8/dist-packages/apex/transformer/pipeline_parallel/__init__.py", line 1, in <module>
    from apex.transformer.pipeline_parallel.schedules import get_forward_backward_func
  File "/usr/local/lib/python3.8/dist-packages/apex/transformer/pipeline_parallel/schedules/__init__.py", line 5, in <module>
    from apex.transformer.pipeline_parallel.schedules.fwd_bwd_no_pipelining import forward_backward_no_pipelining
  File "/usr/local/lib/python3.8/dist-packages/apex/transformer/pipeline_parallel/schedules/fwd_bwd_no_pipelining.py", line 10, in <module>
    from apex.transformer.pipeline_parallel.schedules.common import Batch
  File "/usr/local/lib/python3.8/dist-packages/apex/transformer/pipeline_parallel/schedules/common.py", line 6, in <module>
    from apex.contrib.layer_norm.layer_norm import FastLayerNorm
  File "/usr/local/lib/python3.8/dist-packages/apex/contrib/layer_norm/__init__.py", line 1, in <module>
    from .layer_norm import FastLayerNorm
  File "/usr/local/lib/python3.8/dist-packages/apex/contrib/layer_norm/layer_norm.py", line 5, in <module>
    import fast_layer_norm
ModuleNotFoundError: No module named 'fast_layer_norm'
```

**Comment by TheWispy** [comment] 2022-02-24 12:00
Checking out an older version was a good temporary fix for us.

**Comment by 17Skye17** [comment] 2022-02-24 12:02
> Checking out an older version was a good temporary fix for us.

Same problem here, which version would you recommend?

**Comment by TheWispy** [comment] 2022-02-24 12:06
I've had luck with 2a4ab17776eb530f63ed159deadca13981007468, but I'm yet to properly check whether any more recent versions work.

**Comment by 17Skye17** [comment] 2022-02-25 02:05
> I've had luck with [2a4ab17](https://github.com/NVIDIA/apex/commit/2a4ab17776eb530f63ed159deadca13981007468), but I'm yet to properly check whether any more recent versions work.

Thank you so much! I just find branch `22.01_pp` works for me.
I tried `git clone -b 22.01_pp https://github.com/NVIDIA/apex.git` to solve this problem.

**Comment by ptrblck** [comment] 2022-08-03 07:46
It seems the issue is resolved. Closing

**Closed by ptrblck** 2022-08-03 07:46 UTC
