### ISSUE TITLE
Can't reproduce 20% performance gains on resnet50 using channel last memory format

### ISSUE THREAD

**Issue by Musisoul** [NVIDIA/apex#1445] opened 2022-08-03 05:18 UTC
**Describe the Bug**
In PyTorch document [performance-gains](https://pytorch.org/tutorials/intermediate/memory_format_tutorial.html#performance-gains), the Chapter "Performance Gains" says "We were able to archive over 22% perf gains with channels last comparing to contiguous format, both while utilizing ‘AMP (Automated Mixed Precision)’ training scripts". However, in our A100 machine, the average of velocity is approximately equal between using channels-last or not. We also found that the velocity of baseline is more stable than that of CL. Logs are uploaded in this repo: [channels-last-logs](https://github.com/Musisoul/channels-last-logs).
**Minimal Steps/Code to Reproduce**
`python main_amp.py -a resnet50 --b 200 --workers 16 --opt-level O2  ./data`
`python main_amp.py -a resnet50 --b 200 --workers 16 --opt-level O2 --channels-last true ./data`

**Environment**
PyTorch version: 1.11.0+cu113
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: CentOS Linux 7 (Core) (x86_64)
GCC version: (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)
Clang version: Could not collect
CMake version: version 2.8.12.2
Libc version: glibc-2.17

Python version: 3.7.11 (default, Jul 27 2021, 14:32:16) [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-3.10.0-957.el7.x86_64-x86_64-with-centos-7.6.1810-Core
Is CUDA available: True
CUDA runtime version: 9.0.176
GPU models and configuration:
GPU 0: A100-SXM-80GB
GPU 1: A100-SXM-80GB
GPU 2: A100-SXM-80GB
GPU 3: A100-SXM-80GB
GPU 4: A100-SXM-80GB
GPU 5: A100-SXM-80GB
GPU 6: A100-SXM-80GB
GPU 7: A100-SXM-80GB

Nvidia driver version: 460.32.03
cuDNN version: Probably one of the following:
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn.so.8.1.1
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8.1.1
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn_adv_train.so.8.1.1
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8.1.1
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8.1.1
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8.1.1
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn_ops_train.so.8.1.1
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.21.5
[pip3] spring==0.7.2+cu112.torch1110.mvapich2.nartgpu.develop.805601a8
[pip3] torch==1.11.0+cu113
[pip3] torchvision==0.12.0+cu113
[conda] numpy 1.21.5 pypi_0 pypi
[conda] spring 0.7.0+cu112.torch1110.mvapich2.pmi2.nartgpu pypi_0 pypi
[conda] torch 1.11.0+cu113 pypi_0 pypi
[conda] torchvision 0.12.0+cu113 pypi_0 pypi

**Comment by ptrblck** [comment] 2022-08-03 07:15
I cannot reproduce the issue and see a significant speedup of:
* channels_first: ~1450 img/s
* channels_last: ~2150 img/s

Outputs:
```
# channels_first
Epoch: [0][100/6406]	Time 0.139 (0.239)	Speed 1442.537 (836.478)	Loss 7.0084223747 (7.0538)	Prec@1 0.000 (0.150)	Prec@5 2.000 (0.700)
Epoch: [0][110/6406]	Time 0.138 (0.230)	Speed 1447.599 (869.862)	Loss 7.0417304039 (7.0527)	Prec@1 0.000 (0.136)	Prec@5 0.000 (0.636)
Epoch: [0][120/6406]	Time 0.139 (0.222)	Speed 1443.442 (899.653)	Loss 6.9943909645 (7.0478)	Prec@1 0.000 (0.125)	Prec@5 1.000 (0.667)
Epoch: [0][130/6406]	Time 0.138 (0.216)	Speed 1449.999 (926.710)	Loss 7.0192046165 (7.0456)	Prec@1 0.000 (0.115)	Prec@5 0.500 (0.654)
Epoch: [0][140/6406]	Time 0.138 (0.210)	Speed 1451.487 (951.276)	Loss 6.9744200706 (7.0405)	Prec@1 0.000 (0.107)	Prec@5 0.500 (0.643)
Epoch: [0][150/6406]	Time 0.138 (0.205)	Speed 1451.955 (973.659)	Loss 6.9265947342 (7.0330)	Prec@1 0.000 (0.100)	Prec@5 0.500 (0.633)

# channels_last
Epoch: [0][100/6406]	Time 0.093 (0.256)	Speed 2139.686 (781.233)	Loss 7.0625724792 (7.0541)	Prec@1 0.000 (0.050)	Prec@5 0.000 (0.400)
Epoch: [0][110/6406]	Time 0.093 (0.241)	Speed 2149.048 (829.213)	Loss 6.9155750275 (7.0415)	Prec@1 0.000 (0.045)	Prec@5 1.000 (0.455)
Epoch: [0][120/6406]	Time 0.093 (0.229)	Speed 2148.310 (873.930)	Loss 7.0468397141 (7.0420)	Prec@1 0.000 (0.042)	Prec@5 0.000 (0.417)
Epoch: [0][130/6406]	Time 0.093 (0.218)	Speed 2150.206 (915.741)	Loss 7.0014915466 (7.0389)	Prec@1 0.500 (0.077)	Prec@5 0.500 (0.423)
Epoch: [0][140/6406]	Time 0.094 (0.209)	Speed 2137.605 (954.722)	Loss 6.9758772850 (7.0344)	Prec@1 0.500 (0.107)	Prec@5 1.000 (0.464)
Epoch: [0][150/6406]	Time 0.094 (0.202)	Speed 2135.887 (991.267)	Loss 6.9816174507 (7.0308)	Prec@1 0.000 (0.100)	Prec@5 0.000 (0.433)
```
Note that your logs indicate a similar performance, but especially your channels_last run is unstable and it seems your system cannot keep the GPU busy:
```
Epoch: [0][140/6406]	Time 0.251 (0.216)	Speed 797.589 (926.640)	Loss 6.9565415382 (7.0270)	Prec@1 0.500 (0.071)	Prec@5 1.500 (0.429)
Epoch: [0][150/6406]	Time 0.097 (0.208)	Speed 2060.467 (961.928)	Loss 6.9756922722 (7.0235)	Prec@1 0.000 (0.067)	Prec@5 0.000 (0.400)
Epoch: [0][160/6406]	Time 0.305 (0.214)	Speed 654.861 (934.540)	Loss 6.9866609573 (7.0212)	Prec@1 0.500 (0.094)	Prec@5 0.500 (0.406)
Epoch: [0][170/6406]	Time 0.233 (0.215)	Speed 857.663 (929.639)	Loss 6.9556403160 (7.0174)	Prec@1 0.500 (0.118)	Prec@5 1.000 (0.441)
Epoch: [0][180/6406]	Time 0.098 (0.209)	Speed 2047.100 (958.713)	Loss 6.8811097145 (7.0098)	Prec@1 0.500 (0.139)	Prec@5 1.500 (0.500)
Epoch: [0][190/6406]	Time 0.260 (0.211)	Speed 770.611 (946.552)	Loss 6.9194593430 (7.0051)	Prec@1 0.000 (0.132)	Prec@5 1.500 (0.553)
Epoch: [0][200/6406]	Time 0.098 (0.206)	Speed 2039.007 (972.608)	Loss 6.8988704681 (6.9997)	Prec@1 0.000 (0.125)	Prec@5 1.000 (0.575)
Epoch: [0][210/6406]	Time 0.218 (0.206)	Speed 918.256 (969.874)	Loss 6.9623966217 (6.9980)	Prec@1 0.000 (0.119)	Prec@5 1.000 (0.595)
Epoch: [0][220/6406]	Time 0.316 (0.211)	Speed 632.169 (946.882)	Loss 6.9273929596 (6.9948)	Prec@1 0.000 (0.114)	Prec@5 1.000 (0.614)
Epoch: [0][230/6406]	Time 0.097 (0.206)	Speed 2071.142 (969.769)	Loss 6.9117360115 (6.9911)	Prec@1 0.000 (0.109)	Prec@5 0.500 (0.609)
Epoch: [0][240/6406]	Time 0.186 (0.205)	Speed 1074.158 (973.712)	Loss 6.9108181000 (6.9878)	Prec@1 0.000 (0.104)	Prec@5 1.000 (0.625)
Epoch: [0][250/6406]	Time 0.276 (0.208)	Speed 723.850 (960.451)	Loss 6.8597369194 (6.9827)	Prec@1 0.000 (0.100)	Prec@5 2.500 (0.700)
```
You have a few peaks in the performance which than tanks afterwards, which usually points to e.g. a data loading bottleneck.

Profile you code to see where the bottleneck is coming from and try to get rid if it to feed the samples fast enough to your A100.

Closing, as not reproducible.

**Closed by ptrblck** 2022-08-03 07:15 UTC
Labels: bug
