### ISSUE TITLE
Cannot install apex due to Legacy Install Failure

### ISSUE THREAD

**Issue by shicode** [NVIDIA/apex#1548] opened 2022-12-01 19:09 UTC
When I try to install apex using the command below, I get a legacy-install-failure error 

`pip install -v --disable-pip-version-check --no-cache-dir --deprecated_fused_adam --global-option="--cpp_ext" --global-option="--cuda_ext" ./`

Output:

` 
File "<string>", line 2, in <module>
    File "<pip-setuptools-caller>", line 34, in <module>
    File "/home/shilpa/Desktop/ASP/apex/setup.py", line 64, in <module>
      check_cuda_torch_binary_vs_bare_metal(torch.utils.cpp_extension.CUDA_HOME)
    File "/home/shilpa/Desktop/ASP/apex/setup.py", line 50, in check_cuda_torch_binary_vs_bare_metal
      raise RuntimeError("Cuda extensions are being compiled with a version of Cuda that does " +
  RuntimeError: Cuda extensions are being compiled with a version of Cuda that does not match the version used to compile Pytorch binaries.  Pytorch binaries were compiled with Cuda 11.3.
  In some cases, a minor-version mismatch will not cause later errors:  https://github.com/NVIDIA/apex/pull/323#discussion_r287021798.  You can try commenting out this check (at your own risk).
  error: subprocess-exited-with-error
  
  × Running setup.py install for apex did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: /home/shilpa/anaconda3/envs/ASP/bin/python -u -c '
  exec(compile('"'"''"'"''"'"'
  # This is <pip-setuptools-caller> -- a caller that pip uses to run setup.py
  #
  # - It imports setuptools before invoking setup.py, to enable projects that directly
  #   import from `distutils.core` to work with newer packaging standards.
  # - It provides a clear error message when setuptools is not installed.
  # - It sets `sys.argv[0]` to the underlying `setup.py`, when invoking `setup.py` so
  #   setuptools doesn'"'"'t think the script is `-c`. This avoids the following warning:
  #     manifest_maker: standard file '"'"'-c'"'"' not found".
  # - It generates a shim setup.py, for handling setup.cfg-only projects.
  import os, sys, tokenize
  
  try:
      import setuptools
  except ImportError as error:
      print(
          "ERROR: Can not execute `setup.py` since setuptools is not available in "
          "the build environment.",
          file=sys.stderr,
      )
      sys.exit(1)
  
  __file__ = %r
  sys.argv[0] = __file__
  
  if os.path.exists(__file__):
      filename = __file__
      with tokenize.open(__file__) as f:
          setup_py_code = f.read()
  else:
      filename = "<auto-generated setuptools caller>"
      setup_py_code = "from setuptools import setup; setup()"
  
  exec(compile(setup_py_code, filename, "exec"))
  '"'"''"'"''"'"' % ('"'"'/home/shilpa/Desktop/ASP/apex/setup.py'"'"',), "<pip-setuptools-caller>", "exec"))' --cpp_ext --cuda_ext install --record /tmp/pip-record-bb1n75tf/install-record.txt --single-version-externally-managed --compile --install-headers /home/shilpa/anaconda3/envs/ASP/include/python3.10/apex
  cwd: /home/shilpa/Desktop/ASP/apex/
  Running setup.py install for apex ... error
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> apex

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

`

Running cuda version 11.4 with a compatible pytorch version on Ubuntu

**Comment by crcrpar** [comment] 2022-12-01 19:19
> File "/home/shilpa/Desktop/ASP/apex/setup.py", line 64, in
> check_cuda_torch_binary_vs_bare_metal(torch.utils.cpp_extension.CUDA_HOME)
> File "/home/shilpa/Desktop/ASP/apex/setup.py", line 50, in check_cuda_torch_binary_vs_bare_metal
> raise RuntimeError("Cuda extensions are being compiled with a version of Cuda that does " +
> RuntimeError: Cuda extensions are being compiled with a version of Cuda that does not match the version used to compile Pytorch binaries. Pytorch binaries were compiled with Cuda 11.3.
> In some cases, a minor-version mismatch will not cause later errors: [#323 (comment)](https://github.com/NVIDIA/apex/pull/323#discussion_r287021798). You can try commenting out this check (at your own risk).
> error: subprocess-exited-with-error

Could you try following the issue and comment mentioned in the error message?

**Comment by shicode** [comment] 2022-12-01 19:21
@crcrpar I did. It didn't fix the issue

**Comment by mayank31398** [comment] 2022-12-02 20:53
Seeing the same issue :)

**Comment by ipostr08** [comment] 2022-12-09 09:11
Same problem.

**Comment by ClaudiaSchulz** [comment] 2022-12-16 12:54
Same problem

**Comment by hijkzzz** [comment] 2023-01-01 07:29
Same problem

**Comment by ee2110** [comment] 2023-01-06 06:46
Hi, I got the same issue and commenting out the checking still persists error. However, I was able to solve it by reinstalling the PyTorch CUDA version that matches with requirements.

For example, I got the error:
`The detected CUDA version (11.6) mismatches the version that was used to compile PyTorch (10.2). Please make sure to use the same CUDA versions.`

Therefore, I reinstall the specific PyTorch version from here:
https://pytorch.org/get-started/previous-versions/

After that, I manage to install apex again although I got a bunch of warning lines.

**Comment by ptrblck** [comment] 2023-01-26 10:12
> I have solved this problem by reinstall the CUDA (nvcc toolkit) of the same version of PyTorch.

> However, I was able to solve it by reinstalling the PyTorch CUDA version that matches with requirements.

That's good to hear as it's the right solution.
Closing

**Closed by ptrblck** 2023-01-26 10:12 UTC
Labels: bug

**Comment by BehnamSherafat** [comment] 2023-01-29 07:56
> 

I did the same as you but it takes so long to install Apex and as you said many warnings and weird logs!! I don't know if it installs Apex correctly or not!

**Comment by BehnamSherafat** [comment] 2023-01-29 07:56
> Hi, I got the same issue and the error still persists if merely commented out the checking. However, I was able to solve it by reinstalling the PyTorch CUDA version that matches with requirements.
> 
> For example, I got the error: `The detected CUDA version (11.6) mismatches the version that was used to compile PyTorch (10.2). Please make sure to use the same CUDA versions.`
> 
> Therefore, I reinstall the specific PyTorch version from here: https://pytorch.org/get-started/previous-versions/
> 
> After that, I manage to install apex again although I got a bunch of warning lines.

I did the same as you but it takes so long to install Apex and as you said many warnings and weird logs!! I don't know if it installs Apex correctly or not!

**Comment by narked165** [comment] 2023-06-15 21:19
It is pretty easy to fix this.  The issue is the legacy versioning in requirements.txt
fastapi==0.59.0
xmltodict==0.12.0
pydantic==1.6.1
uvicorn==0.13.4
uvloop==0.15.2
gunicorn==20.0.4
httptools==0.1.1

I just used pip install <package name (ie. fastapi)> One at a time.  I suppose, alternatively, you could remove the sempher versioning, in requirements, as well.  

uvicorn rrdrest:rrd_rest --host "127.0.0.1"
 --port 9000
INFO:     Started server process [2520441]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:9000 (Press CTRL+C to quit)
