### ISSUE TITLE
RuntimeError: "bernoulli_scalar_cuda_" not implemented for 'torch.cuda.HalfTensor'

### ISSUE THREAD

**Issue by jinserk** [NVIDIA/apex#72] opened 2018-11-01 18:47 UTC
Hi,
I've been found that latest PyTorch and latest apex conflict with this error:
```
RuntimeError: "bernoulli_scalar_cuda_" not implemented for 'torch.cuda.HalfTensor'
```
and it requires some remapping the tables in `amp` model. Thank you!

**Comment by mcarilli** [comment] 2018-11-01 21:38
This is a known issue with torch.nn.Dropout.  If you invoke dropout with inplace=False, it should work*.  The root cause is known and a fix should be submitted to upstream soon.  I'll comment again when that happens.

*unfortunately, this will not work for Dropout2d currently, that will need to be run in float.

**Comment by mcarilli** [comment] 2018-11-02 16:50
Half precision dropout has been fixed in current top of tree:
https://github.com/pytorch/pytorch/commit/2f82a0682687552c27f86312de012c95cbb754f5

Hopefully this will resolve your errors.  You shouldn't need to use inplace=False anymore either.

**Comment by jinserk** [comment] 2018-11-02 19:20
Awesome, thank you so much!!

**Comment by ngimel** [comment] 2018-11-02 20:17
It still might be a good idea to use inplace=False, because that will trigger fused kernels for dropout, whereas inplace=True will fall back to a slower implementation. Difference in memory use is not that much.

**Comment by jinserk** [comment] 2018-11-03 14:00
Oh I didn't know that, thanks @ngimel !

**Closed** 2018-11-10 20:56 UTC
