### ISSUE TITLE
Error: identifier "CUDA_R_16BF" is undefined

### ISSUE THREAD

**Issue by Ellinier** [NVIDIA/apex#1310] opened 2022-02-26 08:05 UTC
Hi,
I use the following code to install the apex:
`pip install -v --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" ./`
and I faced some error as below:
```
/tmp/pip-req-build-x8qe1ygy/csrc/megatron/fused_weight_gradient_dense_16bit_prec_cuda.cu(33): error: identifier "CUDA_R_16BF" is undefined
    1 error detected in the compilation of "/tmp/tmpxft_00002af7_00000000-6_fused_weight_gradient_dense_16bit_prec_cuda.cpp1.ii".
```
It compiles with cuda information as follows:
```
Compiling cuda extensions with
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Wed_Oct_23_19:24:38_PDT_2019
Cuda compilation tools, release 10.2, V10.2.89
from /usr/local/cuda/bin
```

Can anyone help me?

**Comment by Bruce-Ch** [comment] 2022-02-26 12:53
Facing the same problem. Hope someone could help.

**Comment by Bruce-Ch** [comment] 2022-02-26 14:38
I figured it out by using cuda@11.3 instead of cuda@10.2. Maybe this problem only exists for cuda@10.2.

**Comment by ptrblck** [comment] 2022-08-03 07:47
Yes, you need to install CUDA11.x for `bfloat16` support. Closing as the issue is resolved.

**Closed by ptrblck** 2022-08-03 07:47 UTC
