### ISSUE TITLE
Warning:  apex was installed without --cuda_ext.

### ISSUE THREAD

**Issue by amuier** [NVIDIA/apex#86] opened 2018-11-21 09:24 UTC
I install apex according this sentence:

> python setup.py install --cuda_ext --cpp_ext

2.After that, using 

> import apex

 to test, but it report warning as following:
Warning:  apex was installed without --cuda_ext. Fused syncbn kernels will be unavailable.  Python fallbacks will be used instead.
Warning:  apex was installed without --cuda_ext.  FusedAdam will be unavailable.
Warning:  apex was installed without --cuda_ext.  FusedLayerNorm will be unavailable.

Is there any problem?

**Comment by mcarilli** [comment] 2018-11-21 16:45
Ok, that is a little strange.  If the --cuda-ext and --cpp_ext options are working as intended, you should have seen c++ and cuda files being built as part of the install (long gcc and nvcc command lines).  Did you see these?

**Comment by mcarilli** [comment] 2018-12-04 17:46
I just received a new notification from this issue, but I don't see any new information posted.  Is everything working on your end?  Can I close this?

**Comment by matthew-z** [comment] 2018-12-06 18:20
Hi, I have the same problem: I set the flags when installing and I confirmed that there is  `fused_adam.py` in `apex/build/lib.linux-x86_64-3.6/apex/optimizers`. 

However, I still have the warning.

Environment: 
Ubuntu18.04+CUDA10.0+CUDNN7.4.1+python3.6.6
I installed pytorch 1.0 by compiling from source.

**Comment by yaysummeriscoming** [comment] 2018-12-07 16:00
@matthew-z weird, for me apex isn't giving warnings & my setup is the same as yours, except that I'm using ubuntu 16.04 minimal.

**Comment by matthew-z** [comment] 2018-12-07 18:10
@yaysummeriscoming @amuier 

It seems that apex relies on the latest pytorch C++ API.  Installing the latest nightly pytorch and rebuilding  apex again (remember to clean apex/build) can solve this problem

**Comment by yaysummeriscoming** [comment] 2018-12-07 18:20
@matthew-z interesting, good to know!  There seems to be a huge amount of work going on in pytorch right now.

**Comment by matthew-z** [comment] 2018-12-07 19:44
@mcarilli 

Very excited to see 1.0 finally get released.

I didn't record the exact commit hash, but I think I build it around Nov.7

Actually, I imported optimizers in the apex/apex directory. I guess it is not the issue as currently I can import optimizers successfully after re-building pytorch, but you are correct I should do "import apex.optimizers" outside the apex repository.

**Closed** 2018-12-12 18:05 UTC

**Comment by enod** [comment] 2019-01-11 07:00
With pytorch version 1.0, I'm still getting the warnings:
```
Warning:  apex was installed without --cuda_ext. Fused syncbn kernels will be unavailable.  Python fallbacks will be used instead.
Warning:  apex was installed without --cuda_ext.  FusedAdam will be unavailable.
Warning:  apex was installed without --cuda_ext.  FusedLayerNorm will be unavailable.
```

**Comment by mcarilli** [comment] 2019-01-18 17:14
Did you see C++ and gcc output during the install process?  Try this:
```
pip uninstall apex
cd apex
rm -rf build (if it exists)
python setup.py install --cuda_ext --cpp_ext 
```
You should see something like https://gist.github.com/mcarilli/18a44f2988ec9e3ee03e452b5fa2432a#file-output-txt-L69-L93 if the cpp and cuda extensions are actually being built.

**Comment by tstandley** [comment] 2019-01-18 18:55
I don't get the cpp output. I discovered this line in the output that I got:
Warning:  nvcc is not available.  Ignoring --cuda-ext
I tried:
sudo apt install nvidia-cuda-toolkit
But it resulted in the apex installer having C++ errors. It installed nvcc
9.1 though, which might be why.

Part of the beauty of Pytorch is that you don't have to install CUDA. How
important are these extensions for performance?

**Comment by tstandley** [comment] 2019-01-18 18:57
I don't get the cpp output. I discovered this line in the output that I got:
`Warning:  nvcc is not available.  Ignoring --cuda-ext`
I tried:
`sudo apt install nvidia-cuda-toolkit`
But it resulted in the apex installer having C++ errors. It installed nvcc
9.1 though, which might be why.

Part of the beauty of Pytorch is that you don't have to install CUDA. How
important are these extensions for performance?

**Comment by mcarilli** [comment] 2019-01-18 19:20
That's true, if you install Pytorch from the conda package (which is a static binary that contains all the cuda runtime code statically linked in) you only need the cuda driver on your system to use GPUs.  You don't actually need nvcc accessible.

If you wish to install the extensions on bare metal, you can get cuda 10 from [the official download page](https://developer.nvidia.com/cuda-downloads).  I think the easiest way forward is to use a devel container, as outlined [here](https://github.com/NVIDIA/apex/issues/112#issuecomment-453307010).

The performance impact of the extensions varies based on your application.  If you're only using apex.parallel.DistributedDataParallel, it isn't much.  If you're using sync batchnorm, it will be significant.  I don't believe FusedAdam or FusedLayerNorm have Python fallbacks either, so these will be unavailable.

**Comment by mangotree3** [comment] 2019-01-29 02:02
I got this problem too and managed to solve it. In my case, the problem was that the apex module fused_adam_cuda was calling the wrong path to a cuda directory (/usr/local/cuda/lib) that had been previously installed and therefore couldn't find the file libcudart.so.9.1. The file was actually located in another directory /usr/local/cuda/lib64. I changed the env variable LD_LIBRARY_PATH include the new path and everything works since then. 

The way the .__init__ of apex is coded makes it a bit tricky to find the problem. There is a try/except trying to import the module optimizers. Even if the optimizers module exists and has been well installed, it will return that --cuda-ext is not installed if the optimizers module cannot be imported correctly.

Hope this helps anyone who has the same problem.

**Comment by PistonY** [comment] 2019-08-12 03:37
I also got this issue.
But I success with
```shell
pip uninstall apex
cd apex
rm -rf build (if it exists)
python setup.py install --cuda_ext --cpp_ext 
```
What the different between using
```shell
git clone https://github.com/NVIDIA/apex
cd apex
pip install -v --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" ./
```
@mcarilli

**Comment by KokeCacao** [comment] 2019-08-14 22:11
I got
```
Warning:  multi_tensor_applier fused unscale kernel is unavailable, possibly because apex was installed without --cuda_ext --cpp_ext. Using Python fallback.  Original ImportError was: ImportError('/home/k1412042720/miniconda3/envs/ml/lib/$
ython3.7/site-packages/amp_C.cpython-37m-x86_64-linux-gnu.so: undefined symbol: __cudaPopCallConfiguration') 
```
only when I installed with
```
$ git clone https://github.com/NVIDIA/apex
$ cd apex
$ pip install -v --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" ./
```
Here is my env
```
__Python VERSION: 3.7.3 | packaged by conda-forge | (default, Jul  1 2019, 21:52:21)               
[GCC 7.3.0]                                                                                                                                                                                                                                    
__pyTorch VERSION: 1.1.0                                                                                                                                                                                                                       
__CUDA VERSION: 9.0.176                                                                                                                                                                                                                        
__CUDNN VERSION: 7501                                                                                                                                                                                                                          
__Number CUDA Devices: 1
Available devices: 1                                                                                                                                                                                                                           
Current cuda device: 0
```

**Comment by ptrblck** [comment] 2019-08-14 22:48
@KokeCacao Did you check, if the installation was successful using this command?
Could you try to reinstall apex and make sure no old `apex` versions are installed in your current environment.

**Comment by KokeCacao** [comment] 2019-08-14 23:17
> @KokeCacao Did you check, if the installation was successful using this command?
> Could you try to reinstall apex and make sure no old `apex` versions are installed in your current environment.

Thank you for your reply.

I didn't check whether my installation was successful, but I assume the program will delete unsuccessful installations anyway. Since I commented out the `if (bare_metal_major != torch_binary_major) or (bare_metal_minor != torch_binary_minor)` statement under `def check_cuda_torch_binary_vs_bare_metal(cuda_dir)` during the installation, this might be where the warning is coming from -- I am not certain.

**Comment by ptrblck** [comment] 2019-08-15 00:31
Which CUDA version are you using locally (`nvcc --version`) and which one shipped with PyTorch?
It's generally not recommended to remove this check and the warning might indeed come from this fact.

**Comment by KokeCacao** [comment] 2019-08-15 01:30
```
>>> import subprocess
>>> import torch
>>> from torch.utils.cpp_extension import CUDAExtension
>>> subprocess.check_output([torch.utils.cpp_extension.CUDA_HOME + "/bin/nvcc", "-V"], universal_newlines=True)
'nvcc: NVIDIA (R) Cuda compiler driver\nCopyright (c) 2005-2018 NVIDIA Corporation\nBuilt on Tue_Jun_12_23:07:04_CDT_2018\nCuda compilation tools, release 9.2, V9.2.148\n'
```

```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Tue_Jun_12_23:07:04_CDT_2018
Cuda compilation tools, release 9.2, V9.2.148
```

**Comment by ptrblck** [comment] 2019-08-15 12:33
@KokeCacao Could you install the latest PyTorch binaries with CUDA9.2?
You can find the install instructions [here](https://pytorch.org/get-started/locally/).

**Comment by KokeCacao** [comment] 2019-08-15 20:47
> @KokeCacao Could you install the latest PyTorch binaries with CUDA9.2?
> You can find the install instructions [here](https://pytorch.org/get-started/locally/).

```
  cudatoolkit                                9.0-h13b8566_0 --> 9.2-0
  pytorch              1.1.0-py3.7_cuda9.0.176_cudnn7.5.1_0 --> 1.2.0-py3.7_cuda9.2.148_cudnn7.6.2_0
  torchvision                        0.3.0-py37_cu9.0.176_1 --> 0.4.0-py37_cu92
```

I still got the same problem after updating

```
Warning:  multi_tensor_applier fused unscale kernel is unavailable, possibly because apex was installed without --cuda_ext --cpp_ext. Using Python fallback.  Original ImportError was: ImportError('libcudart.so.9.0: cannot open shared object file: No such file or directory')
```

**Comment by ptrblck** [comment] 2019-08-16 13:47
The `ImportError` points to `libcudart.so.9.0`.
Could you rebuild apex and make sure that your `nvcc` 9.2 is being used?

**Comment by KokeCacao** [comment] 2019-08-17 00:10
> The `ImportError` points to `libcudart.so.9.0`.
> Could you rebuild apex and make sure that your `nvcc` 9.2 is being used?

It worked after rebuild. Thank you for your patient explanation.

**Comment by ferryjoker** [comment] 2019-08-28 08:30
I got
No module named 'amp_C'
after i installed successfully

**Comment by ptrblck** [comment] 2019-08-28 11:19
@ferryjoker Could you try to reinstall it and post the install log here, please?

**Comment by ferryjoker** [comment] 2019-08-28 11:58
![image](https://user-images.githubusercontent.com/41275116/63853732-07093280-c9ce-11e9-9f20-81fd2130adfa.png)
 I reinstall it and find new error...

**Comment by ptrblck** [comment] 2019-08-28 12:01
You are missing the `./` at the end of the install command:
```
pip install -v --no-cache-dir ./
# or for full performance and functionality
pip install -v --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" ./
```

**Comment by ferryjoker** [comment] 2019-08-28 12:08
Thank you for your patient explanation.
![image](https://user-images.githubusercontent.com/41275116/63854247-556b0100-c9cf-11e9-85ec-6a2f0f625277.png)
but there is another error and this time i type the right command

**Comment by ptrblck** [comment] 2019-08-28 12:12
Could you post the complete log by wrapping it into three backticks ```?

**Comment by ferryjoker** [comment] 2019-08-28 12:19
```RuntimeError: Cuda extensions are being compiled with a version of Cuda that does not match the version used to compile Pytorch binaries.  Pytorch binaries were compiled with Cuda 9.0.176.
    In some cases, a minor-version mismatch will not cause later errors:  https://github.com/NVIDIA/apex/pull/323#discussion_r287021798.  You can try commenting out this check (at your own risk).
  Running setup.py install for apex ... error
Cleaning up...
  Removing source in /tmp/pip-req-build-x3mm9720
Removed build tracker '/tmp/pip-req-tracker-003uce68'
ERROR: Command "/home/zhangshuchen/anaconda3/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-req-build-x3mm9720/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' --cpp_ext --cuda_ext install --record /tmp/pip-record-i0lukdyw/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-req-build-x3mm9720/
```

**Comment by ptrblck** [comment] 2019-08-28 13:07
The CUDA version shipped with the PyTorch binaries do not match your local CUDA install.
If just the minor version creates the mismatch, you could comment the condition as described in the error message. Otherwise it is recommended to install the matching CUDA version on your machine.

**Comment by kwea123** [comment] 2019-10-15 02:31
I got these warnings:
```
Warning:  using Python fallback for SyncBatchNorm, possibly because apex was installed without --cuda_ext.  The exception raised when attempting to import the cuda backend was:  No module named 'syncbn'
Warning:  apex was installed without --cpp_ext.  Falling back to Python flatten and unflatten.
```

When it is written `using Python fallback` does it just mean that the performance would not be as good, or the functionality is broken? For example the first one does it mean it just uses a slower version of SyncBatchNorm or it doesn't use SyncBatchNorm at all? It doesn't matter much if it just runs slower..

**Comment by jiangnanyida** [comment] 2019-11-07 07:58
I have the same problem when import apex on colab.
execute the code
`learner.fit(4, lr=args['learning_rate'], schedule_type="warmup_linear")
`
first is the warning 
`Warning:  apex was installed without --cpp_ext.  Falling back to Python flatten and unflatten.`

it seems that it fails to find the path of fp16_optimizer and FusedAdam, but the wdir is apex 
`ImportError: cannot import name 'FP16_Optimizer'`
`ImportError: Please install apex from https://www.github.com/nvidia/apex`

**Comment by ptrblck** [comment] 2019-11-10 21:28
It should run slower using the Python fallback.

**Comment by RSKothari** [comment] 2020-05-15 14:31
@ptrblck the pitfalls of python fall-back aren't exactly clear. Is it safe to assume that only speed is impacted?

**Comment by IsakWesterlundBitville** [comment] 2020-06-02 14:59
I had the same problem but it fixed itself after reinstalling cuda 10.2

**Comment by tisbuet** [comment] 2021-11-06 15:17
> You are missing the `./` at the end of the install command:
> 
> ```
> pip install -v --no-cache-dir ./
> # or for full performance and functionality
> pip install -v --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" ./
> ```

Thanks buddy! It has worked perfectly.

**Comment by Mamooshe** [comment] 2023-09-12 16:51
Hi guys.
I wanna install apex in google drive. when I run bellow command this error happens.

!git clone https://github.com/NVIDIA/apex
%cd apex/
!pip3 install -v --disable-pip-version-check --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext"  --global-option="--xentropy" --global-option="--fast_multihead_attn" ./
